name: "Send weekly email to the on-call"
on:
  # Necessary to test the workflow on PRs.
  pull_request:
  # Send on push so that the on-call get an updated report, if needed.
  push:
    branches:
      - master
  schedule:
    # Send out the report every Sunday at noon PST
    - cron:  '0 20 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ros-security/github-contribution-report-generator@0.0.7
      with:
        authors-filter: |
          dabonnie
          emersonknapp
          gauravgh
          jaisontj
          jikawa-az
          lichenbo
          mm318
          murphm8
          prajakta-gokhale
          r-meagher
          raghaprasad
          ryanewel
          samuelgundry
          thomas-moulard
          xabxx
          zmichaels11
        organizations-filter: |
          ament
          colcon
          ros
          ros-infrastructure
          ros-security
          ros-tooling
          ros2
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        since-n-days-ago: 7
        file-name: weekly-report
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: html-report
        path: weekly-report.html
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: markdown-report
        path: weekly-report.md
